let gridzone = `/*
Theme Name: Gridzone
Theme URI: http://alx.media/themes/gridzone/
Version: 1.3.0
Requires at least: 5.0
Requires PHP: 5.6
Tested up to: 5.5
Description: <a href="http://alx.media/themes/gridzone/">Gridzone</a> is a flexible portfolio theme with plenty of options. It is optimized for all devices and built to work with blocks. You can choose between light and dark theme, widget sidebar to the left or right - or no sidebar at all. Demo: http://demo.alx.media/x/?theme=Gridzone
Author: Alexander Agnarson
Author URI: http://alx.media
Tags: portfolio, photography, blog, one-column, two-columns, right-sidebar, left-sidebar, custom-colors, custom-menu, featured-images, flexible-header, full-width-template, post-formats, sticky-post, theme-options, threaded-comments, translation-ready, custom-logo, custom-header, custom-background
Text Domain: gridzone

	Copyright: (c) 2018 Alexander "Alx" Agnarson
	License: GNU General Public License v3.0
	License URI: http://www.gnu.org/licenses/gpl-3.0.html
*/

/*
WARNING! DO NOT EDIT THIS FILE!
To make it easy to update your theme, you should not edit the styles in this file. Instead use a child theme
to add your styles. You can copy a style from this file and paste it in the child theme's style.css and it
will override the style in this file. You have been warned! :)
*/

/* ------------------------------------------------------------------------- *
 *  Table of contents
	
	1. Reset
	2. Base Styles
		- Fonts
		- Forms
		- Entry Text
		- Headings
	3. Base Structure
		- Layout
	4. Common Elements
		- Nav
	5. Header
	6. Page
	7. Footer
	8. Post Entry
	9. Post Formats
	10. Widgets
	11. Comments
	12. Plugins
	13. Slick Carousel
	
/* ------------------------------------------------------------------------- */

/* ------------------------------------------------------------------------- *
 *  Reset - http://meyerweb.com/eric/tools/css/reset/ v2.0 | 20110126
 * ------------------------------------------------------------------------- */
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, 
pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, 
samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, 
fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, 
canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, 
section, summary, time, mark, audio, video { margin: 0; padding: 0; border: 0; font-size: 100%; font: inherit; vertical-align: baseline; }
article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {	display: block; }
ol, ul { list-style: none; }
blockquote, q { quotes: none; }
blockquote:before, blockquote:after, q:before, q:after { content: ''; content: none; }
table { border-collapse: collapse; border-spacing: 0; }


/* ------------------------------------------------------------------------- *
 *  Base Styles
/* ------------------------------------------------------------------------- */
body { background: #f5f5f5; font-size: 15px; line-height: 1.5em; color: #444; font-weight: 300; }
::selection { background: #333; color: #fff; }
::-moz-selection { background: #333; color: #fff; }
a { color: #333; text-decoration: none; }
a:hover { color: #333; }
img { max-width: 100%; height: auto; }
a,
a:before,
a:after { transition-property: background color; transition-duration: 0.2s; transition-timing-function: ease; }
a img { transition: opacity 0.2s ease; }
address,cite,em { font-style: italic; }
strong { font-weight: 600; }
.left,.alignleft { float: left; }
.right,.alignright { float: right; }
.aligncenter { margin-left: auto; margin-right: auto; }

/*  base : clear
/* ------------------------------------ */
.clear { clear: both; display: block; overflow: hidden; visibility: hidden; width: 0; height: 0; }
.group:before, .group:after { content: ""; display: table; }
.group:after { clear: both; }
.group { zoom: 1; }

/*  base : font awesome square size
/* ------------------------------------ */
.fa, .fab, .fal, .far, .fas { width: 1em; text-align: center; }

/*  base : fonts
/* ------------------------------------ */
body { font-family: "Titillium", Arial, sans-serif; }

@font-face {
	font-family: 'Titillium';
	src: url('fonts/titillium-light-webfont.eot');
	src: url('fonts/titillium-light-webfont.svg#titillium-light-webfont') format('svg'),
		 url('fonts/titillium-light-webfont.eot?#iefix') format('embedded-opentype'),
		 url('fonts/titillium-light-webfont.woff') format('woff'),
		 url('fonts/titillium-light-webfont.ttf') format('truetype');
	font-weight: 300;
	font-style: normal;
}
@font-face {
	font-family: 'Titillium';
	src: url('fonts/titillium-lightitalic-webfont.eot');
	src: url('fonts/titillium-lightitalic-webfont.svg#titillium-lightitalic-webfont') format('svg'),
		 url('fonts/titillium-lightitalic-webfont.eot?#iefix') format('embedded-opentype'),
		 url('fonts/titillium-lightitalic-webfont.woff') format('woff'),
		 url('fonts/titillium-lightitalic-webfont.ttf') format('truetype');
	font-weight: 300;
	font-style: italic;
}
@font-face {
	font-family: 'Titillium';
	src: url('fonts/titillium-regular-webfont.eot');
	src: url('fonts/titillium-regular-webfont.svg#titillium-regular-webfont') format('svg'),
		 url('fonts/titillium-regular-webfont.eot?#iefix') format('embedded-opentype'),
		 url('fonts/titillium-regular-webfont.woff') format('woff'),
		 url('fonts/titillium-regular-webfont.ttf') format('truetype');
	font-weight: 400;
	font-style: normal;
}
@font-face {
	font-family: 'Titillium';
	src: url('fonts/titillium-regularitalic-webfont.eot');
	src: url('fonts/titillium-regularitalic-webfont.svg#titillium-regular-webfont') format('svg'),
		 url('fonts/titillium-regularitalic-webfont.eot?#iefix') format('embedded-opentype'),
		 url('fonts/titillium-regularitalic-webfont.woff') format('woff'),
		 url('fonts/titillium-regularitalic-webfont.ttf') format('truetype');
	font-weight: 400;
	font-style: italic;
}
@font-face {
    font-family: 'Titillium';
    src: url('fonts/titillium-semibold-webfont.eot');
    src: url('fonts/titillium-semibold-webfont.svg#titillium-semibold-webfont') format('svg'),
         url('fonts/titillium-semibold-webfont.eot?#iefix') format('embedded-opentype'),
         url('fonts/titillium-semibold-webfont.woff') format('woff'),
         url('fonts/titillium-semibold-webfont.ttf') format('truetype');
	font-weight: 600;
	font-style: normal;
}

/*  base : forms
/* ------------------------------------ */
input, textarea, button, select, label { font-family: inherit; }
.themeform input,
.themeform select,
.themeform textarea,
.themeform button,
.themeform label { font-size: 14px; }
.themeform input::-moz-focus-inner, 
.themeform button::-moz-focus-inner { border: 0; padding: 0; }
.themeform input[type="search"],
.themeform input[type="text"],
.themeform input[type="password"],
.themeform input[type="email"],
.themeform input[type="url"],
.themeform input[type="tel"],
.themeform input[type="number"],
.themeform input[type="submit"],
.themeform select,
.themeform button, 
.themeform textarea { margin: 0; -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box; -webkit-border-radius: 0; border-radius: 0; }
.themeform input, 
.themeform select,
.themeform textarea, 
.themeform button { -moz-appearance: none; -webkit-appearance: none; -moz-transition: all .2s ease; -webkit-transition: all .2s ease; transition: all .2s ease; }
.themeform select { appearance: normal; -moz-appearance: menulist; -webkit-appearance: menulist; }
.themeform input[type="checkbox"] { -moz-appearance: checkbox; -webkit-appearance: checkbox; }
.themeform input[type="radio"] { -moz-appearance: radio; -webkit-appearance: radio; }
.themeform label { font-weight: 600; color: #333; }
.themeform input[type="search"],
.themeform input[type="text"], 
.themeform input[type="password"], 
.themeform input[type="email"], 
.themeform input[type="url"],
.themeform input[type="tel"],
.themeform input[type="number"],
.themeform select,
.themeform textarea { background: #fff; border: 2px solid #e5e5e5; color: #777; display: block; max-width: 100%; outline: none; padding: 7px 8px; }
.themeform input[type="search"]:focus,
.themeform input[type="text"]:focus, 
.themeform input[type="password"]:focus, 
.themeform input[type="email"]:focus, 
.themeform input[type="url"]:focus,
.themeform input[type="tel"]:focus,
.themeform input[type="number"]:focus, 
.themeform select:focus,
.themeform textarea:focus { border-color: #ddd; color: #333; -webkit-box-shadow: 0 0 3px rgba(0,0,0,0.1); box-shadow: 0 0 3px rgba(0,0,0,0.1); }
.themeform label .required { color: #333; }
.themeform input[type="button"],
.themeform input[type="reset"],
.themeform input[type="submit"],
.themeform button[type="button"],
.themeform button[type="reset"],
.themeform button[type="submit"] { background: #333; color: #fff; padding: 8px 14px; font-weight: 600; display: inline-block; border: none; cursor: pointer; -webkit-border-radius: 3px; border-radius: 3px; }
.themeform input[type="button"]:hover,
.themeform input[type="reset"]:hover,
.themeform input[type="submit"]:hover,
.themeform button[type="button"]:hover,
.themeform button[type="reset"]:hover,
.themeform button[type="submit"]:hover { background: #333; }

.themeform.searchform div { position: relative; }
.themeform.searchform div input { background: #fff; padding-left: 26px; line-height: 20px; }
.themeform.searchform div:after { color: #ccc; line-height: 24px; font-size: 14px; content: "\f002"; position: absolute; left: 10px; top: 6px; font-family: "Font Awesome 5 Free"; font-weight: 900; }

/*  base : entry
/* ------------------------------------ */
.entry { font-size: 19px; line-height: 1.6em; }
.entry a { color: #000; box-shadow: 0 1px 0 #999; }
.entry a:hover { box-shadow: 0 1px 0 #000; }
.entry hr { border: 0; background: #e5e5e5; height: 2px; width: 30%; margin: 40px auto; }
.entry p,
.entry dd { margin-bottom: 1em; }
.entry dt { color: #333; }
.entry dt { font-weight: 600;}
.entry address { margin-bottom: 1em; }
.entry blockquote { position: relative; color: #777; font-style: italic; margin: 0 0 20px 0; padding-left: 50px; }
.entry blockquote p { font-weight: 400; color: #444; margin-bottom: 0.75em; }
.entry blockquote:before { content: "\f10d"; color: #ccc; font-size: 32px; font-style: normal; font-family: "Font Awesome 5 Free"; font-weight: 900; text-align: center; position: absolute; left: 0; top: 0; }
.entry blockquote.twitter-tweet:before { content: "\f099"; }
.entry code, .entry pre { font-family: Monaco, "Courier New", "DejaVu Sans Mono", "Bitstream Vera Sans Mono", monospace; font-size: 11px; }
.entry pre { background: url(img/pre.png) repeat top; padding: 18px 20px; margin: 30px 0; border: 1px solid #ddd; line-height: 19px; white-space: pre-wrap; word-wrap: break-word; overflow-x: auto; overflow-y: hidden; }
.entry code { background: #ddd; padding: 0 3px; }
.entry ins { background: #fff486; }
.entry sub,
.entry sup { font-size: 62.5%; }
.entry sub { vertical-align: sub; }
.entry sup { vertical-align: super; }

/* image position & caption */
.entry img.size-auto,
.entry img.size-large,
.entry img.size-medium,
.entry attachment img { max-width: 100%; height: auto; }
.entry img.alignleft { margin: 18px 20px 18px 0; }
.entry img.alignright { margin: 18px 0 18px 20px; }
.entry img.aligncenter { margin: 18px auto; clear: both; display: block; }
.entry img .size-full { width: 100%!important; }
.entry .gallery img, .entry img.wp-smiley { margin: 0; }
.entry .wp-caption { background: #f1f1f1; max-width: 100%; margin-bottom: 14px; padding-top: 5px; text-align: center; }
.entry .wp-caption-text { font-style: italic; }
.entry .wp-caption a { border-bottom: none; }
.entry .wp-caption img { margin: 0; max-width: 100%; height: auto; }
.entry .wp-caption.alignleft { margin-right: 20px; }
.entry .wp-caption.alignright { margin-left: 20px; }
.entry .wp-caption.alignnone { overflow: hidden; }
.entry .wp-caption.alignnone img { margin: 0 auto; max-width: 100%!important; }
.entry .wp-caption-text { color: #999; font-size: 13px; padding: 0 0 8px 0; margin: 0; }

/* table */
.entry table { font-size: 14px; margin-bottom: 1.5em; width: 100%; text-align: center; }
.entry table tr.alt { background: #eee; }
.entry table td { border: 1px solid #ddd; text-align: center; padding: 5px; vertical-align: middle; }
.entry table th { border: 1px solid #ddd; font-weight: 600; text-align: center; padding: 10px 5px; }

/* default gallery */
.entry .gallery,
.widget .gallery { clear: both; overflow: hidden; width: 100%; margin-top: 15px!important; margin-bottom: 15px!important; }
.entry .gallery img,
.widget .gallery img { display: block; width: 100%; height: auto; border-width: 1px 2px!important; border-color: transparent!important; }
.entry .gallery .gallery-item,
.widget .gallery .gallery-item { position: relative; overflow: hidden; border-color: transparent; margin-top: 0!important; }
.entry .gallery .gallery-caption,
.widget .gallery .gallery-caption { background: rgba(255,255,255,0.8); color: #333; font-size: 13px; line-height: 1.4em; padding: 10px 0; text-align: left; text-indent: 10px; font-style: normal; margin: 0; bottom: -44px; left: 2px; right: 2px; overflow: hidden; position: absolute; text-overflow: ellipsis; white-space: nowrap; width: 100%;
transition: all .2s ease;
-o-transition: all .2s ease;
-moz-transition: all .2s ease;
-webkit-transition: all .2s ease; }
.entry .gallery .gallery-item:hover .gallery-caption  { bottom: 0; }
.entry .gallery-columns-5 .gallery-caption,
.entry .gallery-columns-6 .gallery-caption,
.entry .gallery-columns-7 .gallery-caption,
.entry .gallery-columns-8 .gallery-caption,
.entry .gallery-columns-9 .gallery-caption,
.widget .gallery-columns-2 .gallery-caption,
.widget .gallery-columns-3 .gallery-caption,
.widget .gallery-columns-4 .gallery-caption,
.widget .gallery-columns-5 .gallery-caption,
.widget .gallery-columns-6 .gallery-caption,
.widget .gallery-columns-7 .gallery-caption,
.widget .gallery-columns-8 .gallery-caption,
.widget .gallery-columns-9 .gallery-caption { display: none!important; }

/*  base : headings
/* ------------------------------------ */
.heading,
#reply-title { font-weight: normal; font-size: 18px; font-weight: 600; margin-bottom: 1em; }
.heading i { font-size: 22px; margin-right: 6px; }


/* ------------------------------------------------------------------------- *
 *  Base Blocks
/* ------------------------------------------------------------------------- */

/*  blocks : common
/* ------------------------------------ */

/* block : paragraph */
.entry p { margin-bottom: 32px; }

/* block : heading */
h1, h2, h3, h4, h5, h6 { color: #333; font-weight: 300; -ms-word-wrap: break-word; word-wrap: break-word; }
.entry h1,
.entry h2,
.entry h3,
.entry h4,
.entry h5,
.entry h6 { font-weight: 600; line-height: 1.3em; }
.entry h1 span, 
.entry h2 span, 
.entry h3 span, 
.entry h4 span, 
.entry h5 span, 
.entry h6 span { color: #bbb; }
.entry h1 { font-size: 38px; letter-spacing: -1px; }
.entry h2 { font-size: 34px; letter-spacing: -0.7px; }
.entry h3 { font-size: 28px; letter-spacing: -0.5px; }
.entry h4 { font-size: 24px; letter-spacing: -0.3px; }
.entry h5 { font-size: 20px; font-weight: 600; }
.entry h6 { font-size: 16px; font-weight: 600; text-transform: uppercase; }

/* block : list */
.entry ol,
.entry ul { margin: 0 0 15px 30px; padding-left: 30px; }
.entry ol ol,
.entry ol ul,
.entry ul ul,
.entry ul ol { margin-bottom: 0; }
.entry li { margin: 0; }
.entry ul li,
.entry ol ul li { list-style: square; }
.entry ol li,
.entry ol ul ol li { list-style: decimal; }

/* block : common */
.entry .wp-block-image figcaption,
.entry .wp-block-audio figcaption,
.entry .wp-block-embed figcaption { font-size: 14px; text-align: center; }

/* block : image */
.entry .wp-block-image {  }

/* block : gallery */
.entry .wp-block-gallery { padding: 0; margin-left: 0; }
.entry .wp-block-gallery .blocks-gallery-grid { margin: 0; padding: 0; }
.entry .wp-block-gallery .blocks-gallery-item figcaption { box-sizing: border-box; }

/* block : cover */
.entry .wp-block-cover {  }

/* block : quote */
.entry .wp-block-quote { margin-bottom: 20px; }
.entry .wp-block-quote.is-large { padding-left: 50px; }

/* block : audio */
.entry .wp-block-audio {  }

/* block : file */
.entry .wp-block-file {  }
.entry .wp-block-file a.wp-block-file__button { color: #fff; }

/* block : video */
.entry .wp-block-embed {  }

/*  blocks : formatting
/* ------------------------------------ */

/* block : classic */
.entry .wp-block-classic {  }

/* block : pullquote */
.entry .wp-block-pullquote { padding-top: 0; padding-bottom: 0; }
.entry .wp-block-pullquote.alignleft { margin-right: 2em; }
.entry .wp-block-pullquote.alignright { margin-left: 2em; }
.entry .wp-block-pullquote blockquote { padding-left: 50px; text-align: left; }
.entry .wp-block-pullquote blockquote p { line-height: 1.4em; }

/* block : code */
.entry .wp-block-code {  }
.entry .wp-block-code code { background: none; }

/* block : custom html */
.entry .wp-block-custom {  }

/* block : preformatted */
.entry .wp-block-preformatted {  }

/* block : table */
.entry .wp-block-table {  }

/* block : verse */
.entry .wp-block-verse {  }

/*  blocks : layout elements
/* ------------------------------------ */

/* block : separator */
.entry .wp-block-separator {  }

/* block : more */
.entry .more-link {  }

/* block : button */
.entry .wp-block-button {  }
.entry .wp-block-button a { color: #fff; }

/* block : columns */
.entry .wp-block-columns {  }

/* block : media & text */
.entry .wp-block-media-text {  }
.entry .has-large-font-size { line-height: 1.4em; }

/* block : spacer */
.entry .wp-block-spacer {  }

/* block : page break */
.entry .post-pages {  }

/*  blocks : widgets
/* ------------------------------------ */

/* block : latest comments */
.entry .wp-block-latest-comments { padding-left: 0; }

/* block : latest posts */
.entry .wp-block-latest-posts {  }

/* block : archives */
.entry .wp-block-archives {  }

/* block : categories */
.entry .wp-block-categories {  }

/* block : shortcode */
.entry .wp-block-shortcode {  }

/* block : calendar */
.entry .wp-block-calendar {  }

/* block : rss */
.entry .wp-block-rss {  }

/* block : search */
.entry .wp-block-search {  }

/* block : tag cloud */
.entry .wp-block-tag-cloud {  }

/*  blocks : shared
/* ------------------------------------ */
.entry > ol,
.entry > ul,
.entry h1,
.entry h2,
.entry h3,
.entry h4,
.entry h5,
.entry h6,
.entry .wp-block-image,
.entry .wp-block-gallery,
.entry .wp-block-cover,
.entry .wp-block-embed,
.entry .wp-block-quote,
.entry .wp-block-pullquote,
.entry .wp-block-audio,
.entry .wp-block-file,
.entry .wp-block-code,
.entry .wp-block-preformatted,
.entry .wp-block-table,
.entry .wp-block-media-text,
.entry .wp-block-button,
.entry .wp-block-separator,
.entry .wp-block-columns,
.entry .wp-block-latest-comments,
.entry .wp-block-latest-posts,
.entry .wp-block-archives,
.entry .wp-block-categories,
.entry .wp-block-shortcode,
.entry .wp-block-calendar,
.entry .wp-block-rss,
.entry .wp-block-search,
.entry .wp-block-tag-cloud { margin-top: 32px; margin-bottom: 32px; }

/*  blocks : important
/* ------------------------------------ */
.entry > *:not(.alignfull) { max-width: 740px; margin-left: auto; margin-right: auto; box-sizing: border-box; }
.entry > *:not(.alignfull).alignwide { max-width: 940px; }
.entry > .alignfull { margin-left: -40px; margin-right: -40px; max-width: none; width: auto; }


/* ------------------------------------------------------------------------- *
 *  Base Structure
/* ------------------------------------------------------------------------- */

/*  base : layout
/* ------------------------------------ */
#wrapper { min-width: 1024px; height: 100%; overflow: hidden; padding-left: 80px; border-top: 1px solid #fff; }
.container {  }
.container-inner { min-width: 100%; width: 100%; margin: 0 auto; }
.main { }
.main-inner { display: flex; position: relative; min-height: 600px; /* instead of sticky footer */ }
.content { margin: 0 auto; position: relative; width: 100%; padding: 20px; box-sizing: border-box; }
.pad { padding: 30px 50px; }

/* boxed */
body.boxed { background: #eee; }
.boxed #wrapper { background: #fff; max-width: 1380px; margin: 0 auto; box-shadow: 0 0 3px rgba(0,0,0,0.2); }

/*  base : layout columns
/* ------------------------------------ */

/* 2 column, content left */
.col-2cl .main-inner { padding-right: 300px; }
.col-2cl .s1 { margin-right: -300px; order: 2; }
.col-2cl .content { order: 1; }

/* 2 column, content right */
.col-2cr .main-inner { padding-left: 300px; }
.col-2cr .s1 { margin-left: -300px; order: 1; }
.col-2cr .content { order: 2; }

/*  base : sidebar
/* ------------------------------------ */
.sidebar { position: relative; z-index: 2; }
.sidebar .pad { padding-left: 20px; padding-right: 20px; }

/* sidebar primary */
.s1 { width: 300px; z-index: 2; }

/*  base : grid
/* ------------------------------------ */
.grid { margin-right: 3.2%; float: left; display: inline; position: relative; }
.last { clear: right; margin-right: 0!important; }

.one-full { margin-right: 0; width: 100%; }
.one-half { width: 48.4%; }
.one-third { width: 31.2%; }
.two-third { width: 65.6%; }
.one-fourth { width: 22.6%; }
.three-fourth { width: 74.2%; }
.one-fifth { width: 17.4%; }
.two-fifth { width: 38.1%; }
.three-fifth { width: 58.7%; }
.four-fifth { width: 79.4%; }


/* ------------------------------------------------------------------------- *
 *  Common Elements
/* ------------------------------------------------------------------------- */

/*  common : responsive videos
/* ------------------------------------ */
embed, object, iframe { max-width: 100%; }
.video-container { height: auto!important; max-width: 100%!important; text-align: center; }
.video-container iframe { margin: 0 auto; }
.video-container > div { margin: 0 auto; }

/*  common : responsive image + caption
/* ------------------------------------ */
.image-container { position: relative; }
.image-container img { display: block; width: 100%; height: auto; }
.image-caption { background: rgba(0,0,0,0.7); color: #fff; font-size: 13px; line-height: 1.3em; font-style: italic; padding: 8px 10px; position: absolute; bottom: 8px; left: 8px; margin-right: 8px;
-webkit-border-radius: 2px; border-radius: 2px; 
-webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.4), 0 1px 0 rgba(255,255,255,0.03);
box-shadow: inset 0 1px 1px rgba(0,0,0,0.4), 0 1px 0 rgba(255,255,255,0.03); }

/*  common : social links
/* ------------------------------------ */
.social-links { float: right; position: relative; z-index: 2; }
.social-links li { display: inline-block; margin-left: 8px; line-height: 16px; font-size: 0; }
.social-links li a { display: block!important; position: relative; text-align: center; }
.social-links .social-tooltip { color: #333; font-size: 24px; display: inline; position: relative; z-index: 98; }
.social-links .social-tooltip:hover { color: #444; text-decoration: none; }
.social-links .social-tooltip:hover:after { top: -36px; background: #eee; font-size: 14px; color: #666; content: attr(title); display: block; right: 0; padding: 5px 10px; position: absolute; white-space: nowrap; 
-webkit-border-radius: 3px; border-radius: 3px; }
.social-links .social-tooltip:hover:before { top: -10px; right: 8px; border: solid; border-color: #eee transparent; border-width: 5px 5px 0 5px; content: ""; display: block; position: absolute; z-index: 1; }

/*  common : page title
/* ------------------------------------ */
.page-title { padding: 20px; }
.page-title-inner { }
.page-title i { margin-right: 12px; }
.page-title h1,
.page-title h2,
.page-title h3,
.page-title h4 { font-size: 32px; line-height: 1.4em; font-weight: 300; }
.page-title span { color: #999; }
.page-title .notebox { font-size: 18px; font-weight: 300; margin-top: 10px; }

/*  common : notebox
/* ------------------------------------ */
.notebox { position: relative; color: #777; font-size: 15px; line-height: 1.6em; }
.error404 .notebox { margin-bottom: 30px; }
.error404 .notebox input { margin-top: 10px; }
.notebox span { font-weight: 600; }
.notebox .search-again { margin-top: 10px; }
.notebox input[type="text"] { width: 100%; }

/*  common : page image
/* ------------------------------------ */
.page-image { overflow: hidden; position: relative; margin: 0 0 30px 0; }
.page-image-text { position: absolute; top: 50%; margin-top: -35px; width: 100%; text-align: center; }
.page-image-text .caption { color: #fff; font-size: 44px; line-height: 70px; text-transform: uppercase; font-weight: 600; text-shadow: 0 0 20px rgba(0,0,0,0.3); }
.page-image-text .description { display: block; color: #fff; font-size: 15px; line-height: 36px; font-weight: 300; }
.page-image-text .description i { background: rgba(0,0,0,0.7); opacity: 0.9; font-style: normal; padding: 6px 10px; -webkit-border-radius: 2px; border-radius: 2px; }

/*  common : pagination
/* ------------------------------------ */
.pagination { margin: 30px 20px; }
.pagination a { font-size: 18px; font-weight: 600; }
.pagination ul { text-align: center; font-size: 0; }
.pagination ul li { display: inline-block; float: none; }
.pagination ul li a:before { font-family: "Font Awesome 5 Free"; font-weight: 900; font-size: 52px; line-height: 100px; display: block; }
.pagination ul li.next a:before { content: "\f105"; }
.pagination ul li.prev a:before { content: "\f104"; }
.pagination ul li a { display: inline-block; font-size: 0; margin: 10px; width: 100px; height: 100px; border-radius: 10px; background: #fff; box-shadow: 0 0 10px rgba(0,0,0,0.05); }

/*  common : thumb icon
/* ------------------------------------ */
.thumb-icon { background: rgba(0,0,0,0.7); color: #fff; text-align: center; display: block; width: 32px; height: 32px; position: absolute; bottom: 50%; left: 50%; margin-left: -16px; margin-bottom: -16px;
-webkit-border-radius: 4px; border-radius: 4px;
-moz-transition: all 0.7s ease; -webkit-transition: all 0.7s ease; transition: all 0.7s ease;
-webkit-box-shadow: 0 0 2px rgba(255,255,255,0.4);
box-shadow: 0 0 2px rgba(255,255,255,0.4);
-webkit-transform: rotate(45deg);
   -moz-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
     -o-transform: rotate(45deg);
        transform: rotate(45deg); }
.thumb-icon i { font-size: 18px; padding: 7px 0;
-webkit-transform: rotate(-45deg);
   -moz-transform: rotate(-45deg);
    -ms-transform: rotate(-45deg);
     -o-transform: rotate(-45deg);
        transform: rotate(-45deg); }
.thumb-icon .fa-play { margin: -1px 0 0 2px; }
.thumb-icon.small { width: 24px; height: 24px; position: absolute; bottom: 50%; left: 50%; margin: 0 0 -12px -12px;
-webkit-border-radius: 3px; border-radius: 3px; }
.thumb-icon.small i { font-size: 12px; line-height: 16px; padding: 5px 0; }


/* ------------------------------------------------------------------------- *
 *  Section: Header
/* ------------------------------------------------------------------------- */
#header { background: #fff; position: relative; z-index: 99; padding: 0 40px; border-bottom: 1px solid #e5e5e5; box-shadow: 0 0 10px rgba(0,0,0,0.05); }
#header-sticky.sticky-element-sticky { pointer-events: none; }
@media only screen and (min-width: 1081px) {
	#header { pointer-events: auto; -webkit-transition: all 0.25s ease-in-out; transition: all 0.25s ease-in-out; -webkit-transform: translate3d(0, 0, 0); transform: translate3d(0, 0, 0); }
	#header.hide-scroll { -webkit-transform: translateY(-100%); transform: translateY(-100%); }
}

.s2 { background: #fff; position: fixed; top: 0; left: 0; bottom: 0; width: 80px; z-index: 99; box-shadow: 0 0 10px rgba(0,0,0,0.05), 1px 0 rgba(0,0,0,0.05); }
.admin-bar .s2 { top: 32px; }
.s2 .social-links { float: left; margin-top: 20px; width: 100%; }
.s2 .social-links li { margin: 0 auto; padding: 4px 0; width: 100%; position: relative; }
.s2 .social-links li:before { content:""; height: 1px; background: rgba(0,0,0,0.06); position: absolute; left: 30px; right: 30px; top: 0; }
.s2 .social-links li:first-child:before { display: none; }
.s2 .social-links .social-tooltip { display: block; font-size: 20px; padding: 18px 10px; margin: 0 20px; color: rgba(0,0,0,0.7); }
.s2 .social-links .social-tooltip:hover { background: rgba(0,0,0,0.05); box-shadow: inset 0 1px 0 rgba(255,255,255,0.1), inset 0 -1px 0 rgba(255,255,255,0.1), 0 1px 0 rgba(0,0,0,0.1); border-radius: 10px; color: #333; text-decoration: none; }
.s2 .social-links .social-tooltip:active { background: rgba(0,0,0,0.15); box-shadow: inset 0 1px 0 rgba(255,255,255,0.1), inset 0 -1px 0 rgba(255,255,255,0.1), 0 1px 0 rgba(0,0,0,0.1), inset 0 0 10px rgba(255,255,255,0.3); border-radius: 10px; color: #000; text-decoration: none; }
.s2 .social-links .social-tooltip:hover:after { background: #333; color: #fff; padding: 7px 10px; top: 14px; left: 50px; right: auto; }
.s2 .social-links .social-tooltip:hover:before { top: 24px; left: 45px; right: auto; border-color: transparent #333; border-width: 5px 5px 5px 0; }

.site-title { font-size: 36px; font-weight: 300; letter-spacing: -0.5px; float: left; line-height: 60px; padding: 10px 0 10px 0; position: relative; z-index: 2; }
.site-title a { display: block; color: #333; max-width: 100%; }
.site-title a img { display: block; max-width: 100%; max-height: 60px; height: auto; padding: 0; margin: 0 auto; -webkit-border-radius: 0; border-radius: 0; }
.site-description { font-size: 16px; font-weight: 300; color: #aaa; float: left; margin: 30px 0 0 20px; position: relative; z-index: 2; }
.site-header { background: #eee; }
.site-image { display: block; margin: 0 auto; max-height: 400px; }

#profile { position: relative; padding-bottom: 0; padding: 10px 20px 20px; }
#profile-inner { padding-left: 170px; position: relative; z-index: 2; }
#profile-image { margin-left: -170px; float: left; margin-top: 10px; }
#profile-image img { display: block; border-radius: 10px; width: 130px; height: 130px; }
#profile-name { font-size: 32px; font-weight: 300; letter-spacing: -0.7px; line-height: 1.3em; color: #333; padding-top: 12px; margin-bottom: 10px; max-width: 720px; }
#profile-description { font-size: 20px; font-weight: 300; color: #777; letter-spacing: 0; line-height: 1.5em; max-width: 720px; }

/*  header : search
/* ------------------------------------ */
.toggle-search { background: #fff; outline: none; border: 1px solid #eee; width: 60px; color: #333; text-align: center; font-size: 20px; line-height: 24px; cursor: pointer; border-radius: 10px; padding: 16px 0; margin: 10px; display: block; }
.toggle-search:hover { color: #333; }
.toggle-search.active { background: #f1f1f1; color: #333; border-radius: 10px 0 0 10px; }
.toggle-search.active i:before { content: "\f00d"; }
.search-expand { display: none; background: #f1f1f1; padding: 13px 12px 13px 0; position: absolute; top: 10px; left: 70px; width: 340px; border-radius: 0 10px 10px 0; z-index: 10; }
.search-expand-inner {  }
.search-expand .themeform input { background: #fff; width: 100%; border: 1px solid #ddd; }
.search-expand .themeform input:focus { border-color: #ccc; }
.toggle-search.active { padding-top: 18px; padding-bottom: 19px; }
.toggle-search .svg-icon { fill: #333; margin: 0 auto; }
.toggle-search #svg-close { display: none; }
.toggle-search.active #svg-search { display: none; }
.toggle-search.active #svg-close { display: block; }


/* ------------------------------------------------------------------------- *
 *  Section: Navigation
/* ------------------------------------------------------------------------- */

/* menu hamburger */
.menu-toggle-icon { float: right; width: 30px; height: 20px; position: relative; transform: rotate(0deg); transition: .5s ease-in-out; cursor: pointer; }
.menu-toggle-icon span { display: block; position: absolute; height: 2px; width: 100%; background: #333; border-radius: 2px; opacity: 1; left: 0; transform: rotate(0deg); transition: .25s ease-in-out; }
.menu-toggle-icon span:nth-child(1) { top: 0px; transform-origin: left center; }
.menu-toggle-icon span:nth-child(2) { top: 8px; transform-origin: left center; }
.menu-toggle-icon span:nth-child(3) { top: 16px; transform-origin: left center; }
.toggled .menu-toggle-icon span:nth-child(1) { transform: rotate(45deg); top: -2px; left: 5px; }
.toggled .menu-toggle-icon span:nth-child(2) { width: 0%; opacity: 0; }
.toggled .menu-toggle-icon span:nth-child(3) { transform: rotate(-45deg); top: 19px; left: 5px; }

/* menu hide and display */
@media only screen and (min-width: 720px) {
	.mobile-menu #wrap-nav-mobile { display: none; }
}
@media only screen and (max-width: 719px) {
	.mobile-menu #wrap-nav-header { display: none; } 
	#nav-mobile,
	#nav-header { display: none; }
	.mobile #nav-mobile,
	.mobile #nav-header { display: block; }
}

/* menu base */
.nav-menu > .menu-toggle { display: none; }
.nav-menu.mobile > .menu-toggle { display: block; }
.nav-menu.mobile > .menu-toggle ~ * { max-height: 4000px; overflow: hidden; width: 100%; transition: max-height 0.5s cubic-bezier(1, 0, 1, 0); }
.nav-menu.mobile > .menu-toggle[aria-expanded="false"] ~ * { max-height: 0; transition: max-height 0.5s cubic-bezier(0, 1.05, 0, 1); }
.nav-menu .menu,
.nav-menu .menu ul { display: flex; list-style: none; list-style-type: none; margin: 0; padding: 0; }
.nav-menu a { display: block; text-decoration: none; width: 100%; }
.nav-menu.mobile ul { flex-direction: column; }
.nav-menu .menu ul { flex-direction: column; max-width: 0; max-height: 0; overflow: hidden; }
.nav-menu .menu ul.active,
.nav-menu:not(.mobile) .menu li.hover > ul { max-width: 100vw; max-height: 300vh; }
.nav-menu:not(.mobile) .menu .sub-menu { position: absolute; }
.nav-menu .screen-reader-text { display: none; }
.nav-menu .menu-item-wrapper { display: flex; }
.nav-menu { line-height: 20px; }
.nav-menu button { color: inherit; cursor: pointer; font-family: inherit; position: relative; text-align: inherit; user-select: none; background: none; border: none; box-shadow: none; border-radius: 0; font-size: inherit; font-weight: 400; letter-spacing: inherit; padding: 0; text-transform: none; }
.nav-menu.mobile .menu ul { transition: max-height 500ms; max-width: 100%; }

.nav-menu:not(.mobile) .menu { flex-wrap: wrap; justify-content: flex-start; }
.nav-menu:not(.mobile) .menu ul.active,
.nav-menu:not(.mobile) .menu li.hover > ul { overflow: visible; width: 180px; opacity: 1; transform: translateY(0); transition: opacity 0.15s linear, transform 0.15s linear; }
.nav-menu:not(.mobile) .menu ul .sub-menu { left: 200px; top: 0; }
.nav-menu:not(.mobile) .menu { position: relative; }
.nav-menu:not(.mobile) .menu ul { font-size: 15px; opacity: 0; padding: 10px 0; position: absolute; top: calc(100% + 20px); transition: opacity 0.15s linear, transform 0.15s linear, right 0s 0.15s; transform: translateY(6px); z-index: 1; }
.nav-menu:not(.mobile) .menu ul li { position: relative; }
.nav-menu:not(.mobile) .menu ul a { display: block; padding: 7px 20px; transition: background-color 0.15s linear; width: 100%; }
.nav-menu:not(.mobile) .menu li.menu-item-has-children.focus > ul {	min-width: 180px; max-width: 180px; max-height: 300vh; overflow: visible; opacity: 1; transform: translateY(0); transition: opacity 0.15s linear, transform 0.15s linear; }
.nav-menu:not(.mobile) .menu li.menu-item-has-children.focus > ul:focus-within { opacity: 1!important; }
.nav-menu:not(.mobile) .menu li ul.sub-menu:not(.active) { opacity: 0; }
.nav-menu:not(.mobile) .menu li.hover ul.sub-menu:not(.active) { opacity: 1; }
.nav-menu:not(.mobile) .menu li.focus ul ul.sub-menu:not(.active) { opacity: 0; }
.nav-menu:not(.mobile) .menu li.focus ul li.hover ul.sub-menu { opacity: 1; }

.nav-menu:not(.mobile) .menu ul:before,
.nav-menu:not(.mobile) .menu ul:after { content: ""; display: block; position: absolute; bottom: 100%; }
.nav-menu:not(.mobile) .menu ul:before { left: 0; right: 0; height: 20px; }
.nav-menu:not(.mobile) .menu ul:after { border: 8px solid transparent; border-bottom-color: transparent; left: 18px; }
.nav-menu:not(.mobile) .menu ul ul { left: calc(100% + 20px); top: -10px !important; }
.nav-menu:not(.mobile) .menu ul ul:before { bottom: 0; height: auto; left: auto; left: -20px; top: 0; width: 22px; }
.nav-menu:not(.mobile) .menu ul ul:after { border-bottom-color: transparent; bottom: auto; left: -16px; top: 20px; }
.nav-menu-dropdown-left .nav-menu:not(.mobile) .menu ul ul:before { left: auto; right: -20px; }
.nav-menu-dropdown-left .nav-menu:not(.mobile) .menu ul ul { right: calc(100% + 20px); left: auto; }
.nav-menu-dropdown-left .nav-menu:not(.mobile) .menu ul ul:after { border-right-color: transparent; right: -16px; left: auto; }
.nav-menu-dropdown-left .nav-menu:not(.mobile) ul ul button .svg-icon { transform: none; }

.nav-menu:not(.mobile) a,
.nav-menu:not(.mobile) span { transition: all 0.3s ease; }

.nav-menu.mobile { padding: 0; }
.nav-menu.mobile button:focus { outline: none; }
.nav-menu.mobile > button { padding: 16px 20px; float: right; }
.nav-menu.mobile button .svg-icon { transition: all 250ms; }
.nav-menu.mobile button.active .svg-icon { transform: rotate(180deg); }
.nav-menu.mobile ul { border: 0; }
.nav-menu.mobile ul li .menu-item-wrapper { justify-content: space-between; width: 100%; }
.nav-menu.mobile > div > ul > li:last-child { margin-bottom: 52px; }
.nav-menu.mobile ul li a { font-size: 16px; font-weight: 600; padding: 14px 20px; }
.nav-menu.mobile ul ul li a { font-size: 14px; }
.nav-menu.mobile ul ul li a { padding: 12px 0 12px 40px; }
.nav-menu.mobile ul ul ul li a { padding: 12px 0 12px 60px; }
.nav-menu.mobile ul button { margin: 10px 0; padding: 0 20px; }

/* menu styling */
.nav-menu a { color: #fff; }
.nav-menu .svg-icon { fill: #333; }
.nav-menu:not(.mobile) .menu ul { background: #333; color: #fff; border-radius: 4px; }
.nav-menu:not(.mobile) .menu ul:after { border-bottom-color: #333; }
.nav-menu:not(.mobile) .menu ul ul:after { border-right-color: #333; }
.nav-menu-dropdown-left .nav-menu:not(.mobile) .menu ul ul:after { border-left-color: #333; }

.nav-menu:not(.mobile) { font-size: 16px; font-weight: 400; float: right; padding: 12px 0 20px 0; }
.nav-menu:not(.mobile) a { color: #666; }
.nav-menu:not(.mobile) a:hover { color: #333; }
.nav-menu:not(.mobile) ul ul a:hover { color: #ccc; }
.nav-menu:not(.mobile) ul ul > li:hover > span { background: rgba(255,255,255,0.1); }
.nav-menu:not(.mobile) ul ul a { color: #eee; }
.nav-menu:not(.mobile) button { background: none; color: #666; padding: 0 4px; margin-left: 2px; border-radius: 4px; }
.nav-menu:not(.mobile) button.active { background: #eee; color: #333; }
.nav-menu:not(.mobile) button .svg-icon { fill: #bbb; }
.nav-menu:not(.mobile) ul ul button { background: none; color: #eee; padding: 0 5px; margin: 0 10px 0 0; }
.nav-menu:not(.mobile) ul ul button.active { background: #444; color: #eee; }
.nav-menu:not(.mobile) ul ul button .svg-icon { transform: rotate(-90deg); }
.nav-menu:not(.mobile) .menu > li { margin: 16px 20px 0 0; position: relative; }
.nav-menu:not(.mobile) .menu > li:last-child { margin-right: 0; }
.nav-menu:not(.mobile) .menu a { padding: 0; }

.nav-menu:not(.mobile) li.current_page_item > span > a, 
.nav-menu:not(.mobile) li.current-menu-item > span > a, 
.nav-menu:not(.mobile) li.current-menu-ancestor > span > a, 
.nav-menu:not(.mobile) li.current-post-parent > span > a { color: #333; }
.nav-menu:not(.mobile) ul ul li.current_page_item > span > a, 
.nav-menu:not(.mobile) ul ul li.current-menu-item > span > a, 
.nav-menu:not(.mobile) ul ul li.current-menu-ancestor > span > a, 
.nav-menu:not(.mobile) ul ul li.current-post-parent > span > a { color: #aaa; }

.nav-menu.mobile button.active .svg-icon { fill: #333; }
.nav-menu.mobile ul ul { background: rgba(0,0,0,0.03); }
.nav-menu.mobile ul li .menu-item-wrapper,
.nav-menu.mobile ul ul li .menu-item-wrapper { border-bottom: 1px solid rgba(0,0,0,0.07); }
.nav-menu.mobile ul li a { color: #333; }
.nav-menu.mobile ul button,
.nav-menu.mobile ul ul button { border-left: 1px solid rgba(0,0,0,0.07); }
.nav-menu.mobile > div > ul { border-top: 1px solid rgba(0,0,0,0.07); }


/* ------------------------------------------------------------------------- *
 *  Section: Page
/* ------------------------------------------------------------------------- */
#page { }

.slick-image-slide-wrapper { position: relative; }
.slick-image-slide { background: #333; }
.slick-image-slide .slick-slide > div > div { display: block!important; }
.slick-image-slide .slick-slide { position: relative; }
.slick-image-slide .slick-slide img { margin: 0 auto; }
.slick-image-slide-nav { position: absolute; text-align: center; margin-top: -10px; position: absolute; left: 0; right: 0; top: 50%; z-index: 99; pointer-events: none; }
.slick-image-slide-nav .slick-prev { float: left; }
.slick-image-slide-nav .slick-next { float: right; }
.slick-image-slide-nav .slick-prev,
.slick-image-slide-nav .slick-next { background: #eee; transition: all 0.3s ease; position: relative; display: inline-block; margin: 10px; height: 34px; width: 34px; border-radius: 4px; pointer-events: auto; }
.slick-image-slide-nav .slick-prev:hover,
.slick-image-slide-nav .slick-next:hover,
.slick-image-slide-nav .slick-prev:focus,
.slick-image-slide-nav .slick-next:focus { background: #e5e5e5; }
.slick-image-slide-nav .slick-prev { left: 0; }
.slick-image-slide-nav .slick-next { right: 0; }
.slick-image-slide-nav .slick-prev:before { color: #000; font-family: "Font Awesome 5 Free"; font-weight: 900; content: "\f053"; }
.slick-image-slide-nav .slick-next:before { color: #000; font-family: "Font Awesome 5 Free"; font-weight: 900; content: "\f054"; }
.slick-image-slide-dots { background: red; }
.slick-image-slide-dots .slick-dots li { height: 10px; width: 10px; margin: 0 3px; }
.slick-image-slide-dots .slick-dots li button { background: rgba(0,0,0,0.2); height: 10px; width: 10px; border-radius: 100%; text-indent: -9999px; overflow: hidden; }
.slick-image-slide-dots .slick-dots .slick-active button { background: rgba(0,0,0,0.7); }

.post-format { position: relative; }

.front-widgets { margin: 20px; padding: 20px 0; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5; }
.front-widget-col { width: 50%; float: left; }
.front-widget-inner { margin-right: 30px; }
.front-widgets .widget { padding-top: 20px; padding-bottom: 20px; }
.front-widgets .widget > h3 {  }


/* ------------------------------------------------------------------------- *
 *  Section: Footer
/* ------------------------------------------------------------------------- */
#footer { color: #777; position: relative; padding-bottom: 70px; border-top: 1px solid #e5e5e5; }
#footer .pad { padding-bottom: 20px; }

#footer-ads { background: #fff; text-align: center; padding: 10px 0; border-bottom: 1px solid #e5e5e5; }
#footer-ads .widget { padding-bottom: 0; font-size: 0; line-height: 0; }
#footer-ads h3 { display: none; }

#footer-widgets { border-bottom: 1px solid #e5e5e5; }
#footer-widgets .widget { padding: 20px 0; }

#footer-bottom { position: relative; z-index: 99; text-align: center; }
#footer-bottom img { box-shadow: none; }
#footer-bottom .pad { padding-top: 20px; }
#footer-bottom a { color: #444; }
#footer-bottom a:hover { color: #333; }
#footer-bottom #footer-logo { display: inline-block; margin-bottom: 20px; max-height: 60px; -webkit-border-radius: 0; border-radius: 0; }
#footer-bottom #copyright,
#footer-bottom #credit { color: #666; font-weight: 300; line-height: 1.6em; }
#footer-bottom #back-to-top { border: 1px solid #e5e5e5; border-top: 0; color: #333; padding: 10px 0; overflow: hidden; text-align: center; width: 60px; height: 30px; display: block; margin: 0 auto; margin: 0 auto 0; border-radius: 0 0 10px 10px; }
#footer-bottom #back-to-top i { font-size: 38px; position: relative; top: -7px; }
#footer-bottom #back-to-top:hover { color: #333; }
#footer-bottom .social-links { padding-top: 40px; float: none; }
#footer-bottom .social-links a { color: #444; }
#footer-bottom .social-links a:hover { color: #333; }
#footer-bottom .social-links li { margin: 0 6px; }
#footer-bottom .social-links .social-tooltip { font-size: 22px; }
#footer-bottom .social-links .social-tooltip:hover:after { background: #333; color: #fff; }
#footer-bottom .social-links .social-tooltip:hover:before { border-color: #333 transparent; }


/* ------------------------------------------------------------------------- *
 *  Post Entry
/* ------------------------------------------------------------------------- */
.sticky {}
.page .content > article,
.single .content > article { padding: 20px; }
.post-wrapper { background: #fff; box-shadow: 0 0 10px rgba(0,0,0,0.05); margin: 0 auto; max-width: 940px; border-radius: 10px; width: 100%; overflow: hidden; }

.masonry { display: flex; flex-wrap: wrap; justify-content: space-between; }
.masonry-item { width: 25%; padding: 20px; box-sizing: border-box; }
.masonry-item .masonry-inner { background: #fff; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.05); transition: all 0.2s ease-in; }
.masonry-item .entry-top { position: relative; overflow: hidden; }
.masonry-item .entry-thumbnail { display: block; position: relative; }
.masonry-item .entry-thumbnail:before { opacity: 0.01; background: url(img/image-gradient.png) repeat-x; background-size: 100% 100%; content: ""; position: absolute; display: block; height: 100%; width: 100%; bottom: 0; display: block; transition: all .4s ease; pointer-events: none; }
.masonry-item:hover .entry-thumbnail:before,
.masonry-item .entry-thumbnail:focus:before { opacity: 0.4; }
.masonry-item:hover .thumb-icon { background: #fff; color: #333; }
.masonry-item .entry-category { background: transparent; color: #bbb; opacity: 0; position: absolute; left: 0; right: 0; bottom: -100px; padding: 20px 20px 14px; pointer-events: none; transition: all 0.3s ease; }
.masonry-item .entry-category a { background: rgba(0,0,0,0.6); color: #bbb; font-size: 14px; display: inline-block; padding: 3px 11px; border-radius: 10px; margin-bottom: 4px; pointer-events: auto; }
.masonry-item .entry-category a:hover,
.masonry-item .entry-category a:focus { background: #eee; color: #333; }
.masonry-item:hover .entry-category,
.masonry-item:focus-within .entry-category { bottom: 0; opacity: 1; }
.masonry-item img { border-radius: 10px 10px 0 0; display: block; width: 100%; }
.masonry-item .entry-title { padding: 20px 20px 0; }
.masonry-item .entry-title a { display: block; font-size: 16px; font-weight: 600; }
.masonry-item .entry-excerpt { font-size: 14px; padding: 10px 20px 0; color: #999; }
.masonry-item .entry-meta { font-size: 14px; padding: 14px 20px; color: #999; }
.masonry-item .entry-meta li { float: left; margin-right: 20px; }
.masonry-item .entry-meta li a { color: #999; } 
.masonry-item .entry-meta li i { margin-right: 4px; }

.entry-header,
.entry-media,
.entry-footer { max-width: 740px; padding-right: 40px; padding-left: 40px; margin-right: auto; margin-left: auto; }
.entry-content { padding-right: 40px; padding-left: 40px; }

.entry-header { margin: 40px auto 20px; position: relative; }
.entry-header .entry-title { font-weight: 300; font-size: 50px; line-height: 1.3em; letter-spacing: -1px; margin-bottom: 20px; margin-right: 40px; }
.entry-header .entry-title a { color: #333; }
.entry-header .entry-title a:hover { color: #000; }
.entry-header .entry-meta { font-weight: 300; font-size: 16px; color: #999; }
.entry-header .entry-meta a { color: #999; }
.entry-header .entry-meta i { margin-right: 6px; }
.entry-header .entry-meta span { margin-right: 10px; }
.entry-header .entry-meta .entry-category a { display: inline-block; background: #eee; padding: 4px 10px; margin-bottom: 3px; border-radius: 10px; }
.entry-header .entry-meta .entry-category a:hover { background: #e5e5e5; color: #777; }

.entry-media { max-width: 1920px; margin-bottom: 40px; padding-left: 0; padding-right: 0; }
.entry-content {  }
.entry-footer { margin-top: 40px; margin-bottom: 40px; }

.entry-bar { -webkit-transition: all 0.25s ease-in-out; transition: all 0.25s ease-in-out; -webkit-transform: translate3d(0, 0, 0); transform: translate3d(0, 0, 0); }
.entry-bar.hide-scroll { -webkit-transform: translateY(100%); transform: translateY(100%); }



/* ------------------------------------------------------------------------- *
 *  Single
/* ------------------------------------------------------------------------- */

/*  single : sharrre
/* ------------------------------------ */
.sharrre-container { border: 1px solid #eee; border-radius: 10px; margin-bottom: 40px; overflow: hidden; }
.sharrre-container > span { display: none; }
.post-sharrre { margin-top: 30px; }
.sharrre { width: 25%; float: left; }
.sharrre .box { display: block; padding: 16px 20px; }
.sharrre .count { width: 60%; background: #eee; color: #fff; display: block; font-size: 15px; font-weight: 900; line-height: 30px; position: relative; text-align: center; border-radius: 6px; }
.sharrre .count:after { content:''; display: block; position: absolute; right: -12px; width: 0; height: 0; border: solid 6px transparent; border-left-color: #eee; bottom: 9px; }
.sharrre .share { width: 20%; margin-left: 20%; display: block; font-size: 24px; font-weight: 600; line-height: 32px; padding: 0; text-align: center; text-decoration: none; }
.sharrre .share,
.sharrre .count,
.sharrre .count:after { float: left; -webkit-transition: all .3s ease; transition: all .3s ease; }
.sharrre .box:hover { background: #fff!important; }
.sharrre .box:hover .share {}
.sharrre .box:hover .count { color: #fff!important; }

.sharrre#twitter .box:hover { background: #eef6f9; }
.sharrre#twitter .box { border-bottom-color: #24a5db; }
.sharrre#twitter .box:hover .count:after { border-left-color: #24a5db; }
.sharrre#twitter .count,
.sharrre#twitter .share,
.sharrre#twitter .box:hover .count { color: #24a5db; }
.sharrre#twitter .box:hover .count { background: #24a5db; }

.sharrre#facebook .box:hover { background: #f0f2f7; }
.sharrre#facebook .box { border-bottom-color: #3b5998; }
.sharrre#facebook .box:hover .count:after { border-left-color: #3b5998; }
.sharrre#facebook .count,
.sharrre#facebook .share,
.sharrre#facebook .box:hover .count { color: #3b5998; }
.sharrre#facebook .box:hover .count { background: #3b5998; }

.sharrre#pinterest .box:hover { background: #fbf1f0; }
.sharrre#pinterest .box { border-bottom-color: #ca2128; }
.sharrre#pinterest .box:hover .count:after { border-left-color: #ca2128; }
.sharrre#pinterest .count,
.sharrre#pinterest .share,
.sharrre#pinterest .box:hover .count { color: #ca2128; }
.sharrre#pinterest .box:hover .count { background: #ca2128; }

.sharrre#linkedin .box:hover { background: #f2f8fb; }
.sharrre#linkedin .box { border-bottom-color: #0077b5; }
.sharrre#linkedin .box:hover .count:after { border-left-color: #0077b5; }
.sharrre#linkedin .count,
.sharrre#linkedin .share,
.sharrre#linkedin .box:hover .count { color: #0077b5; }
.sharrre#linkedin .box:hover .count { background: #0077b5; }

/*  single : post pages
/* ------------------------------------ */
.post-pages { font-weight: 600; margin-bottom: 20px; }

/*  single : tags
/* ------------------------------------ */
.post-tags { margin: 0 0 60px; }
.post-tags span { font-size: 14px; color: #999; display: inline-block; margin: 0 7px 0 0; }
.post-tags a { background: #eee; display: inline-block; white-space: nowrap; font-size: 14px; color: #999; padding: 1px 7px; margin: 0 5px 6px 0;
-webkit-border-radius: 3px; border-radius: 3px; }
.post-tags a:hover { background-color: #e5e5e5; color: #777; }

/*  single : author bio
/* ------------------------------------ */
.author-bio { background: #f5f5f5; padding: 0 20px 20px; border-radius: 10px; position: relative; color: #777; margin: 40px 0; text-align: center; }
.author-bio .bio-avatar { width: 64px; height: auto; position: relative; display: inline-block; margin-top: -32px; }
.author-bio .bio-avatar:after { background: #333; position: absolute; right: 0; bottom: 0; padding: 4px 4px; content: "\f303"; color: #fff; font-size: 10px; line-height: 12px; width: 12px; font-style: normal; font-family: "Font Awesome 5 Free"; font-weight: 900; text-align: center; border-radius: 100%; }
.author-bio .bio-avatar img { display: block; width: 100%; height: auto; border-radius: 100%; }
.author-bio p { margin-bottom: 8px; }
.author-bio .bio-name { color: #333; font-size: 19px; font-weight: 600; margin: 10px 0; }
.author-bio .bio-desc { color: #777; font-size: 16px; line-height: 1.5em; }

/*  single : related posts
/* ------------------------------------ */

/*  single : post-nav
/* ------------------------------------ */
.post-nav { background: #f5f5f5; border-radius: 10px; margin-bottom: 40px; }
.post-nav li { width: 50%; display: inline; float: left; }
.post-nav li a { position: relative; display: block; padding-top: 10px; padding-bottom: 10px; }
.post-nav li i { color: #ccc; font-size: 18px; position: absolute; top: 50%; margin-top: -10px; }
.post-nav li a strong { display: block; font-size: 12px; color: #aaa; letter-spacing: 0.5px; font-weight: normal; text-transform: uppercase; }
.post-nav li a span { font-size: 15px; font-weight: 600; color: #333; display: block; text-overflow: ellipsis; overflow: hidden; white-space: nowrap; }
.post-nav li a:hover span { color: #000; }
.post-nav li a:hover i { color: #000; }
.post-nav li.previous { float: left; }
.post-nav li.next { float: right; }
.post-nav li.previous a { padding-left: 40px; padding-right: 20px; }
.post-nav li.next a { border-left: 1px solid #eee; padding-left: 20px; padding-right: 40px; }
.post-nav li.previous i { left: 10px; }
.post-nav li.next i { right: 10px; }
.post-nav li a span,
.post-nav li a i { transition-property: background color; transition-duration: 0.2s; transition-timing-function: ease-out; }


/* ------------------------------------------------------------------------- *
 *  Post Formats
/* ------------------------------------------------------------------------- */
.post-format {  }

/*  format : image
/* ------------------------------------ */

/*  format : gallery
/* ------------------------------------ */

/*  format : video
/* ------------------------------------ */

/*  format : audio
/* ------------------------------------ */
.format-audio .post-format iframe { height: 166px; width: 100%; }


/* ------------------------------------------------------------------------- *
 *  Widgets
/* ------------------------------------------------------------------------- */
.widget { color: #777; font-size: 14px; }
.widget a { color: #777; }
.widget a:hover { color: #333; }
.widget > h3 { font-size: 16px; font-weight: 600; margin: 0 -40px 10px; padding: 0 40px; }
.widget > h3 a,
.widget > h3 a:hover { color: #333; }
.widget > h3 a img { display: none; float: left; margin: 3px 7px 0 0; }
.widget select { border: 1px solid #ddd; color: #777; font-size: 15px; padding: 7px; width: 100%; max-width: 100%; }
.widget label.screen-reader-text { display: none; }

.sidebar .widget { background: #fff; box-shadow: 0 0 10px rgba(0,0,0,0.05); padding: 40px; margin-top: 40px; }
.col-2cl .sidebar .widget { border-radius: 10px 0 0 10px; border-right: 0; }
.col-2cr .sidebar .widget { border-radius: 0 10px 10px 0; border-left: 0; }

/*  widgets : icons
/* ------------------------------------ */
.widget > ul li:before,
.widget > ul li a:before,
.widget > div > ul li a:before,
.widget_calendar caption:before { font-family: "Font Awesome 5 Free"; font-weight: 900; font-size: 12px; margin-right: 6px; color: #ccc; display: inline-block!important; width: 1em; text-align: center; }
.widget > ul li a:hover:before { color: #999; }

.widget_archive > ul > li a:before { content: "\f073"; } 
.widget_categories > ul > li a:before { content: "\f07c"; }
.widget_links > ul > li a:before { content: "\f08e"; }
.widget_meta > ul > li a:before { content: "\f0da"; }
.widget_recent_comments > ul > li:before { content: "\f075"; }
.widget_recent_entries > ul > li a:before { content: "\f017"; }
.widget_calendar caption:before { content: "\f073"; }
.widget_pages ul li a:before,
.widget_nav_menu ul li a:before { content: "\f068"; }

/*  widgets : common
/* ------------------------------------ */
.widget_search > h3,
.widget_text > h3,
.widget_tag_cloud > h3,
.widget_calendar > h3 { margin-bottom: 1em; }

.widget_archive ul li, 
.widget_categories ul li, 
.widget_links ul li, 
.widget_meta ul li, 
.widget_recent_comments ul li, 
.widget_recent_entries ul li,
.widget_rss ul li,
.widget_pages ul li a,
.widget_nav_menu ul li a,
.alx-tab li,
.alx-posts li { padding: 7px 0; }

.widget_archive ul li,
.widget_categories ul li,
.widget_links ul li { color: #bbb; }

.widget_recent_comments ul li,
.widget_recent_entries ul li { color: #999; }
.widget_recent_entries .post-date { display: block; }

/*  widget : pages / custom menu
/* ------------------------------------ */
.widget_pages ul li a,
.widget_nav_menu ul li a { display: block; }
.widget_pages li li a,
.widget_nav_menu li li a { padding-left: 15px; }
.widget_pages li li li a,
.widget_nav_menu li li li a { padding-left: 30px; }
.widget_pages ul ul, 
.widget_pages ul ul ul,
.widget_nav_menu ul ul, 
.widget_nav_menu  ul ul ul { border: 0; }

/*  widget : categories
/* ------------------------------------ */
.widget_categories li li { padding-left: 15px; border-bottom: 0; padding-bottom: 0; }
.widget_categories li li li { padding-left: 15px; border-bottom: 0; }
.widget_categories li li a { font-size: 13px; }

/*  widget : rss
/* ------------------------------------ */
.widget_rss ul li a { color: #333; display: block; }
.widget_rss ul li span.rss-date { color: #333; font-weight: 600; display: block; text-transform: uppercase; font-size: 12px; }
.widget_rss ul li cite { color: #999; }

/*  widget : search
/* ------------------------------------ */
.widget_search input.search { color: #999; padding-left: 26px; width: 100%; }
.widget_search .screen-reader-text,
.widget_search #searchsubmit { display: none; }

/*  widget : text
/* ------------------------------------ */
.widget_text .textwidget p { margin-bottom: 1em; }

/*  widget : calendar
/* ------------------------------------ */
.widget_calendar a { color: #333; font-weight: 600; }
.widget_calendar a:hover { color: #333!important; }
.widget_calendar #wp-calendar { width: 100%; }
.widget_calendar caption { background: #333; color: #fff; padding: 5px 10px; }
.widget_calendar caption:before { color: #fff; color: rgba(255,255,255,0.7); font-size: 15px; }
.widget_calendar thead { background: #e2e2e2; -webkit-box-shadow: 0 1px 0 #eee; box-shadow: inset 0 -1px 0 #eee; }
.widget_calendar th { font-weight: 600; }
.widget_calendar th, 
.widget_calendar td { padding: 3px 0; text-align: center; border: 1px solid #e2e2e2; }
.widget_calendar .pad { padding: 0!important; }

/*  custom widget : alxtabs / alxposts
/* ------------------------------------ */
.alx-tabs-nav { margin-bottom: 10px; text-align: center; }
.alx-tabs-nav.tab-count-1 li { width: 100%; }
.alx-tabs-nav.tab-count-2 li { width: 50%; }
.alx-tabs-nav.tab-count-3 li { width: 33.333%; }
.alx-tabs-nav.tab-count-4 li { width: 25%; }
.alx-tabs-nav li { display: block; float: left; }
.alx-tabs-nav li a { color: #999; font-size: 18px; display: block; padding: 14px 0; border-bottom: 1px solid #eee; }
.alx-tabs-nav li a:hover {  }
.alx-tabs-nav li.active a { color: #333; border-bottom-color: #333; }
.alx-tabs-nav li a span { display: none; }

.alx-tab li,
.alx-posts li { font-weight: 300; line-height: 1.4em; }
.alx-tab a,
.alx-posts a { -webkit-transition: all 0.2s ease; -moz-transition: all 0.2s ease; transition: all 0.2s ease; }
.alx-tab img,
.alx-posts img { display: block; width: 100%; height: auto; border-radius: 10px; }
.alx-tab img {  }
.alx-tab.thumbs-enabled li{ padding-left: 62px; }
.alx-tab .tab-item-thumbnail { width: 48px; margin-left: -62px; float: left; }
.alx-tab .tab-item-thumbnail,
.alx-posts .post-item-thumbnail { position: relative; -webkit-transition: all 1s ease; -moz-transition: all 1s ease; transition: all 1s ease; }
.alx-tab.avatars-enabled li{ padding-left: 62px; }
.alx-tab .tab-item-avatar { margin-left: -62px; width: 48px; float: left; -webkit-transition: all 1s ease; -moz-transition: all 1s ease; transition: all 1s ease; }
.alx-tab .tab-item-category,
.alx-posts .post-item-category { color: #aaa; font-size: 14px; }
.alx-tab .tab-item-title a,
.alx-tab .tab-item-comment a,
.alx-posts .post-item-title a { color: #333; }
.alx-tab .tab-item-category a:hover,
.alx-posts .post-item-category a:hover { color: #333!important; }
.alx-tab .tab-item-title,
.alx-tab .tab-item-comment,
.alx-posts .post-item-title { margin: 2px 0; -ms-word-wrap: break-word; word-wrap: break-word; }
.alx-tab .tab-item-date,
.alx-tab .tab-item-name,
.alx-posts .post-item-date  { color: #bbb; font-size: 13px; }
.alx-tab li:hover .tab-item-thumbnail,
.alx-tab li:hover .tab-item-avatar,
.alx-posts li:hover .post-item-thumbnail { opacity: 0.75; }
.alx-tab li:hover .thumb-icon,
.alx-posts li:hover .thumb-icon { background: #fff; color: #111; }

.alx-tab .tab-item-category a,
.alx-posts .post-item-category a,
.alx-tab li:hover .tab-item-title a,
.alx-tab li:hover .tab-item-comment a,
.alx-posts li:hover .post-item-title a { color: #333; }

.alx-posts .post-item-thumbnail { margin-bottom: 10px; }
.alx-posts .post-item-title { font-size: 16px; line-height: 1.5em; }

.s1 .alx-posts .post-item-title { font-size: 18px; line-height: 1.4em; font-weight: 300; }
.s1 .alx-posts .post-item-category,
.s1 .alx-posts .post-item-date { font-size: 13px; }

/*  custom widget : alxvideo
/* ------------------------------------ */
.widget_gridzone_video h3 { margin-bottom: 14px; }


/* ------------------------------------------------------------------------- *
 *  Dark Widgets
/* ------------------------------------------------------------------------- */
.dark .widget { color: rgba(255,255,255,0.6); }
.dark .widget a { color: rgba(255,255,255,0.8); }
.dark .widget a:hover { color: #fff; }
.dark .widget > h3,
.dark .widget > h3 a,
.dark .widget > h3 a:hover { color: #fff; }
.dark .widget select { background: rgba(0,0,0,0.25); border-color: rgba(255,255,255,0.1); color: rgba(255,255,255,0.8); }

/*  widgets : icons
/* ------------------------------------ */
.dark .widget > ul li:before,
.dark .widget > ul li a:before,
.dark .widget > div > ul li a:before  { color: rgba(255,255,255,0.6); opacity: 0.5; }
.dark .widget_calendar caption:before,
.dark .widget > ul li a:hover:before { color: #fff; }

/*  widgets : common
/* ------------------------------------ */
.dark .widget_archive ul li, 
.dark .widget_categories ul li, 
.dark .widget_links ul li, 
.dark .widget_meta ul li, 
.dark .widget_recent_comments ul li, 
.dark .widget_recent_entries ul li,
.dark .widget_rss ul li,
.dark .widget_pages ul li a,
.dark .widget_nav_menu ul li a,
.dark .alx-tab li,
.dark .alx-posts li,
.dark .widget_calendar th, 
.dark .widget_calendar td { border-color: #333; }

.dark .widget_archive ul li,
.dark .widget_categories ul li,
.dark .widget_links ul li,
.dark .widget_recent_comments ul li,
.dark .widget_recent_entries ul li { color: rgba(255,255,255,0.6); }

/*  widget : pages / custom menu
/* ------------------------------------ */

/*  widget : rss
/* ------------------------------------ */
.dark .widget_rss ul li a { color: #fff; }
.dark .widget_rss ul li span.rss-date { color: rgba(255,255,255,0.8); }
.dark .widget_rss ul li cite { color: rgba(255,255,255,0.5); }

/*  widget : search
/* ------------------------------------ */
.dark .widget_search input.search { background: transparent; color: rgba(255,255,255,0.7); border: 1px solid rgba(255,255,255,0.1); }
.dark .widget_search input.search:focus { color: rgba(255,255,255,0.9); }

/*  widget : calendar
/* ------------------------------------ */
.dark .widget_calendar a:hover { color: rgba(255,255,255,0.8)!important; }
.dark .widget_calendar a { color: #fff; }
.dark .widget_calendar thead { background: rgba(0,0,0,0.1); color: #ccc; -webkit-box-shadow: 0 1px 0 rgba(0,0,0,0.1); box-shadow: inset 0 -1px 0 rgba(0,0,0,0.1); }
.dark .widget_calendar caption { background: rgba(255,255,255,0.2); }
.dark .widget_calendar th, 
.dark .widget_calendar td { border-color: rgba(255,255,255,0.1);  }

/*  custom widget : alxtabs / alxposts
/* ------------------------------------ */
.dark .alx-tabs-nav li a { border-color: rgba(255,255,255,0.1); }
.dark .alx-tabs-nav li.active a { color: #fff; border-bottom-color: #fff; }

.dark .alx-tab .tab-item-category a,
.dark .alx-posts .post-item-category a,
.dark .alx-tab li:hover .tab-item-title a,
.dark .alx-tab li:hover .tab-item-comment a,
.dark .alx-posts li:hover .post-item-title a { color: #fff; }
.dark .alx-tab .tab-item-category a:hover,
.dark .alx-posts .post-item-category a:hover { color: rgba(255,255,255,0.8)!important; }

.dark .alx-tab .tab-item-date, 
.dark .alx-tab .tab-item-name, 
.dark .alx-posts .post-item-date { color: rgba(255,255,255,0.5); }


/* ------------------------------------------------------------------------- *
 *  Comments
/* ------------------------------------------------------------------------- */
#comments { margin-top: 20px; }
#pinglist-container { display: none; }

.comment-tabs { margin-bottom: 30px; }
.comment-tabs li { float: left; }
.comment-tabs li a { background: #f5f5f5; border-radius: 10px; font-weight: 600; padding: 10px 14px; margin-bottom: 4px; display: block; color: #aaa; }
.comment-tabs li:first-child a { margin-right: 4px; }
.comment-tabs li a:hover { color: #333; }
.comment-tabs li span { background-color: #fff; padding: 0 6px; margin-left: 8px; -webkit-border-radius: 4px; border-radius: 4px; }
.comment-tabs li i { margin-right: 6px; }
.comment-tabs li.active a { color: #333; border-bottom-color: #333; }

.commentlist, .pinglist { margin-bottom: 20px; }
.commentlist li, .pinglist li { padding-left: 60px; font-size: 14px; line-height: 22px; font-weight: 400; }
.commentlist .comment-body, .pinglist li { clear: both; position: relative; padding-bottom: 15px; }
.commentlist .comment-author,
.commentlist .comment-meta,
.commentlist .comment-awaiting-moderation { font-size: 13px; display: block; float: left; line-height: 20px; }
.commentlist .comment-author { margin-right: 6px; }
.commentlist .fn, .pinglist .ping-link { color: #333; font-size: 13px; font-style: normal; font-weight: 600; }
.commentlist .says { display: none; }
.commentlist .avatar { position: absolute; left: -60px; top: 0; width: 48px; height: 48px; border-radius: 100%; }
.commentlist .comment-meta:before, .pinglist .ping-meta:before { color: #ccc; content: "\f017"; font-family: "Font Awesome 5 Free"; font-weight: 900; font-size: 10px; margin-right: 3px; vertical-align: 4%; } 
.commentlist .comment-meta a, .pinglist .ping-meta { color: #aaa; }
.commentlist .reply { font-size: 13px; line-height: 16px; }
.commentlist .reply a { color: #aaa; }
.commentlist .reply a:hover { color: #333; }
.comment-awaiting-moderation { color: #333; font-style: normal; }

/* pings */
.pinglist li { padding-left: 0; }

/* comment text */
.commentlist .comment-body p { margin-bottom: 8px; color: #777; clear: both; }
.commentlist .comment-body strong { font-weight: bold; }
.commentlist .comment-body em { font-style: italic; }
.commentlist .comment-body ol li { list-style: decimal; margin-left: 2em; padding: 0; }
.commentlist .comment-body ul li { list-style: square; margin-left: 2em; padding: 0; }

/* post author & admin comment */
.commentlist li.bypostauthor > .comment-body:after,
.commentlist li.comment-author-admin > .comment-body:after { background: #333; display: block; position: absolute; content: "\f303"; color: #fff; line-height: 12px; width: 12px; font-style: normal; font-family: "Font Awesome 5 Free"; font-weight: 900; text-align: center; }
.commentlist li.comment-author-admin > .comment-body:after { content: "\f005"; /* star for admin */ }
.commentlist li.bypostauthor > .comment-body:after,
.commentlist li.comment-author-admin > .comment-body:after { top: 32px; left: -28px; font-size: 8px; padding: 2px; border-radius: 100%; }
.commentlist li li.bypostauthor > .comment-body:after,
.commentlist li li.comment-author-admin > .comment-body:after { top: 22px; left: -26px; font-size: 8px; padding: 1px; border-radius: 100%; }

/* child comment */
.commentlist li ul {  }
.commentlist li li { padding-left: 48px; margin: 0; }
.commentlist li li .avatar { width: 36px; height: 36px; left: -48px; top: 0; }
.commentlist li li .comment-meta { left: 70px; }

/*  comments : nav
/* ------------------------------------ */
.comments-nav { margin-bottom: 20px; }
.comments-nav a { font-weight: 600; }
.comments-nav .nav-previous { float: left; }
.comments-nav .nav-next { float: right;  }

/*  comments : form
/* ------------------------------------ */
.logged-in-as,
.comment-notes, 
.form-allowed-tags { display: none; }
#respond { position: relative; }
#reply-title { margin-bottom: 20px; }
li #reply-title { font-size: 0; margin: 0!important; padding: 0; height: 0; border-top: 0; }
#cancel-comment-reply-link { color: #999; display: block; position: absolute; bottom: 26px; right: 20px; font-size: 12px; }
#cancel-comment-reply-link:hover { color: #777; }
#commentform { background: #f5f5f5; padding: 10px 20px 20px; margin-bottom: 15px; border-radius: 10px; }
#commentform p.comment-form-author { width: 48%; float: left; }
#commentform p.comment-form-email { width: 48%; float: right; }
#commentform p.comment-form-url,
#commentform p.comment-form-comment { clear: both; }
#commentform label { padding: 6px 0; font-weight: 600; display: block; }
#commentform input[type="text"], 
#commentform textarea { max-width: 100%; width: 100%; }
#commentform textarea { height: 100px; }
#commentform p.form-submit { margin-top: 10px; }
.logged-in #reply-title { margin-bottom: 20px; }
.logged-in #commentform p.comment-form-comment { margin-top: 10px; }
.logged-in #commentform p.comment-form-comment label { display: none; }
#commentform .comment-form-cookies-consent { padding: 10px 0; }
#commentform .comment-form-cookies-consent label { display: inline; }


/* ------------------------------------------------------------------------- *
 *  Plugins
/* ------------------------------------------------------------------------- */

/*  plugin : wp-pagenavi
/* ------------------------------------ */
.wp-pagenavi { text-align: right; font-weight: 600; line-height: 20px; float: none; margin-right: -2px; text-align: center; }
.wp-pagenavi a,
.wp-pagenavi span { color: #aaa; font-size: 16px; padding: 9px 14px; display: inline-block; margin: 0 1px 10px; }
.wp-pagenavi span.pages { font-size: 16px; font-weight: 400; display: block; margin-bottom: 1em!important; border: none!important; }
.wp-pagenavi span.pages:before { content: "\f15c"; font-family: "Font Awesome 5 Free"; font-weight: 900; margin-right: 6px; }
.wp-pagenavi span.extend { border: none!important; padding-left: 0; padding-right: 0; }
.wp-pagenavi a:hover,
.wp-pagenavi a:active,
.wp-pagenavi span.current { color: #333; }

.wp-pagenavi a { background: #e5e5e5; border-radius: 20px; color: #333; border: none; box-shadow: inset 0 1px 0 rgba(0,0,0,0.05); }
.wp-pagenavi a:hover,
.wp-pagenavi a:active,
.wp-pagenavi span.current { background: #fff; border-radius: 20px; border: none; box-shadow: 0 1px 0 rgba(0,0,0,0.05); }

/*  plugin : contact form 7
/* ------------------------------------ */
.wpcf7 p { font-weight: 600; margin-bottom: 10px; }
.wpcf7 span { display: block; margin-top: 10px; }
.wpcf7 textarea { width: 100%; }
.wpcf7 input[type="text"],
.wpcf7 input[type="password"], 
.wpcf7 input[type="email"],
.wpcf7 input[type="url"],
.wpcf7 input[type="tel"],
.wpcf7 input[type="number"],
.wpcf7 select,
.wpcf7 textarea { background: #f2f2f2; }

/*  plugin : jetpack infinite scroll
/* ------------------------------------ */
.infinite-scroll .infinite-wrap { }
.infinite-scroll #infinite-handle { position: absolute; bottom: -100px; width: 100%; text-align: center; }
.infinite-scroll #infinite-handle span { background: #fff; display: inline-block!important; box-shadow: 0 0 10px rgba(0,0,0,0.05); font-size: 18px; color: #333; font-weight: 600; padding: 20px 26px; border-radius: 10px; }
.infinite-scroll #infinite-handle span:before { font-family: "Font Awesome 5 Free"; font-weight: 900; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; content: "\f067"; margin-right: 10px; }
.infinite-scroll .content { padding-bottom: 160px; }
.infinite-scroll .pagination { display: none; }

/* ------------------------------------------------------------------------- *
 *  Slick Carousel
/* ------------------------------------------------------------------------- */
.slick-slider { position: relative; display: block; box-sizing: border-box; -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; -webkit-touch-callout: none; -khtml-user-select: none; -ms-touch-action: pan-y; touch-action: pan-y; -webkit-tap-highlight-color: transparent;  }
.slick-list { position: relative; display: block; overflow: hidden; margin: 0; padding: 0;  }
.slick-list:focus { outline: none;  }
.slick-list.dragging { cursor: pointer; cursor: hand;  }
.slick-slider .slick-track,.slick-slider .slick-list { -webkit-transform: translate3d(0, 0, 0); -moz-transform: translate3d(0, 0, 0); -ms-transform: translate3d(0, 0, 0); -o-transform: translate3d(0, 0, 0); transform: translate3d(0, 0, 0);  }
.slick-track { position: relative; top: 0; left: 0; display: block; margin-left: auto; margin-right: auto;  }
.slick-track:before,.slick-track:after { display: table; content: '';  }
.slick-track:after { clear: both;  }
.slick-loading .slick-track { visibility: hidden;  }
.slick-slide { display: none; float: left; height: 100%; min-height: 1px;  }
[dir='rtl'] .slick-slide { float: right;  }
.slick-slide img { display: block;  }
.slick-slide.slick-loading img { display: none;  }
.slick-slide.dragging img { pointer-events: none;  }
.slick-initialized .slick-slide { display: block;  }
.slick-loading .slick-slide { visibility: hidden;  }
.slick-vertical .slick-slide { display: block; height: auto; border: 1px solid transparent;  }
.slick-arrow.slick-hidden { display: none;  }


/* ------------------------------------------------------------------------- *
 *  Slick Carousel Theme
/* ------------------------------------------------------------------------- */
.slick-loading .slick-list { background: #fff url(img/ajax-loader.gif) center center no-repeat;  }
.slick-prev,.slick-next { font-size: 0; line-height: 0; position: absolute; top: 50%; display: block; width: 20px; height: 20px; padding: 0; -webkit-transform: translate(0, -50%); -ms-transform: translate(0, -50%); transform: translate(0, -50%); cursor: pointer; color: transparent; border: none; outline: none; background: transparent;  }
.slick-prev:hover,.slick-prev:focus,.slick-next:hover,.slick-next:focus { color: transparent; outline: none; background: transparent;  }
.slick-prev:hover:before,.slick-prev:focus:before,.slick-next:hover:before,.slick-next:focus:before { opacity: 1;  }
.slick-prev.slick-disabled:before,.slick-next.slick-disabled:before { opacity: .25;  }
.slick-prev:before,.slick-next:before { font-family: 'slick'; font-size: 20px; line-height: 1; opacity: .75; color: white; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;  }
.slick-prev { left: -25px;  }
[dir='rtl'] .slick-prev { right: -25px; left: auto;  }
.slick-prev:before { content: '鈫�';  }
[dir='rtl'] .slick-prev:before { content: '鈫�';  }
.slick-next { right: -25px;  }
[dir='rtl'] .slick-next { right: auto; left: -25px;  }
.slick-next:before { content: '鈫�';  }
[dir='rtl'] .slick-next:before { content: '鈫�';  }
.slick-dotted.slick-slider { margin-bottom: 30px;  }
.slick-dots { position: absolute; bottom: -25px; display: block; width: 100%; padding: 0; margin: 0; list-style: none; text-align: center;  }
.slick-dots li { position: relative; display: inline-block; width: 20px; height: 20px; margin: 0 5px; padding: 0; cursor: pointer;  }
.slick-dots li button { font-size: 0; line-height: 0; display: block; width: 20px; height: 20px; padding: 5px; cursor: pointer; color: transparent; border: 0; outline: none; background: transparent;  }
.slick-dots li button:hover,.slick-dots li button:focus { outline: none;  }
.slick-dots li button:hover:before,.slick-dots li button:focus:before { opacity: 1;  }
.slick-dots li button:before { font-family: 'slick'; font-size: 6px; line-height: 20px; position: absolute; top: 0; left: 0; width: 20px; height: 20px; content: '鈥�'; text-align: center; opacity: .25; color: black; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;  }
.slick-dots li.slick-active button:before { opacity: .75; color: black;  }


/* ------------------------------------------------------------------------- *
 *  Accessibility
/* ------------------------------------------------------------------------- */
/* Text meant only for screen readers. */
.screen-reader-text{ border: 0; clip: rect(1px, 1px, 1px, 1px); clip-path: inset(50%); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute!important; width: 1px; word-wrap: normal!important; }
.screen-reader-text:focus { background-color: #fff; border-radius: 3px; box-shadow: 0 0 2px 2px rgba(0, 0, 0, 0.1); clip: auto!important; clip-path: none; color: #333; display: block; font-size: 14px; font-size: 0.875rem; font-weight: bold; height: auto; right: 5px; line-height: normal; padding: 15px 23px 14px; text-decoration: none; top: 5px; width: auto; z-index: 100000; }
/* Do not show the outline on the skip link target. */
#page[tabindex="-1"]:focus{ outline: 0; }
`;